// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Thrive.Modules.Collaboration.Infrastructure.Database;

#nullable disable

namespace Thrive.Modules.Collaboration.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CollaborationContext))]
    [Migration("20240910231835_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("collaboration")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Thrive.Modules.Collaboration.Domain.Member.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Members", "collaboration");
                });

            modelBuilder.Entity("Thrive.Modules.Collaboration.Domain.Workspace.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Roles", "collaboration");
                });

            modelBuilder.Entity("Thrive.Modules.Collaboration.Domain.Workspace.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Workspaces", "collaboration");
                });

            modelBuilder.Entity("Thrive.Modules.Collaboration.Domain.Workspace.ValueObjects.Permission", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Name");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions", "collaboration");
                });

            modelBuilder.Entity("Thrive.Modules.Collaboration.Domain.Member.Entities.Member", b =>
                {
                    b.HasOne("Thrive.Modules.Collaboration.Domain.Workspace.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thrive.Modules.Collaboration.Domain.Workspace.Entities.Role", b =>
                {
                    b.HasOne("Thrive.Modules.Collaboration.Domain.Workspace.Entities.Workspace", null)
                        .WithMany("Roles")
                        .HasForeignKey("WorkspaceId");
                });

            modelBuilder.Entity("Thrive.Modules.Collaboration.Domain.Workspace.Entities.Workspace", b =>
                {
                    b.OwnsOne("Thrive.Modules.Collaboration.Domain.Workspace.Entities.WorkspaceThreads", "WorkspaceThreads", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceId")
                                .HasColumnType("uuid");

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("Workspaces", "collaboration");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId");

                            b1.OwnsMany("Thrive.Modules.Collaboration.Domain.Workspace.Entities.Thread", "Threads", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("CategoryId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<Guid>("WorkspaceId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("WorkspaceId");

                                    b2.ToTable("Thread", "collaboration");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkspaceId");
                                });

                            b1.OwnsMany("Thrive.Modules.Collaboration.Domain.Workspace.Entities.ThreadCategory", "Categories", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Index")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<Guid>("WorkspaceId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("WorkspaceId");

                                    b2.ToTable("ThreadCategory", "collaboration");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkspaceId");
                                });

                            b1.Navigation("Categories");

                            b1.Navigation("Threads");
                        });

                    b.OwnsOne("Thrive.Modules.Collaboration.Domain.Workspace.ValueObjects.WorkspaceName", "Name", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("Workspaces", "collaboration");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("WorkspaceThreads")
                        .IsRequired();
                });

            modelBuilder.Entity("Thrive.Modules.Collaboration.Domain.Workspace.ValueObjects.Permission", b =>
                {
                    b.HasOne("Thrive.Modules.Collaboration.Domain.Workspace.Entities.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("Thrive.Modules.Collaboration.Domain.Workspace.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Thrive.Modules.Collaboration.Domain.Workspace.Entities.Workspace", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
